/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpcomingProjectsRouteImport } from './routes/upcoming-projects'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminHomepageBuilderRouteImport } from './routes/admin.homepage-builder'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReviewQueueRouteImport } from './routes/admin.review-queue'
import { Route as AdminUpcomingProjectsRouteImport } from './routes/admin.upcoming-projects'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminWritersRouteImport } from './routes/admin.writers'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as ReaderIndexRouteImport } from './routes/reader.index'
import { Route as ReaderBookmarksRouteImport } from './routes/reader.bookmarks'
import { Route as ReaderFollowingRouteImport } from './routes/reader.following'
import { Route as ReaderHistoryRouteImport } from './routes/reader.history'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as WriterIndexRouteImport } from './routes/writer.index'
import { Route as WriterAnalyticsRouteImport } from './routes/writer.analytics'
import { Route as WriterProfileRouteImport } from './routes/writer.profile'
import { Route as WriterSeriesRouteImport } from './routes/writer.series'
import { Route as WriterStoriesRouteImport } from './routes/writer.stories'
import { Route as WritersIndexRouteImport } from './routes/writers.index'
import { Route as WritersSlugRouteImport } from './routes/writers.$slug'
import { Route as AdminEditorIndexRouteImport } from './routes/admin.editor.index'
import { Route as AdminWritersIndexRouteImport } from './routes/admin.writers.index'
import { Route as AdminWritersSlugRouteImport } from './routes/admin.writers.$slug'
import { Route as WriterEditorIndexRouteImport } from './routes/writer.editor.index'
import { Route as WriterEditorStoryIdRouteImport } from './routes/writer.editor.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingProjectsRoute = UpcomingProjectsRouteImport.update({
  id: '/upcoming-projects',
  path: '/upcoming-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/admin/faq',
  path: '/admin/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomepageBuilderRoute = AdminHomepageBuilderRouteImport.update({
  id: '/admin/homepage-builder',
  path: '/admin/homepage-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewQueueRoute = AdminReviewQueueRouteImport.update({
  id: '/admin/review-queue',
  path: '/admin/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpcomingProjectsRoute = AdminUpcomingProjectsRouteImport.update({
  id: '/admin/upcoming-projects',
  path: '/admin/upcoming-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWritersRoute = AdminWritersRouteImport.update({
  id: '/admin/writers',
  path: '/admin/writers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const ReaderIndexRoute = ReaderIndexRouteImport.update({
  id: '/reader/',
  path: '/reader/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderBookmarksRoute = ReaderBookmarksRouteImport.update({
  id: '/reader/bookmarks',
  path: '/reader/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderFollowingRoute = ReaderFollowingRouteImport.update({
  id: '/reader/following',
  path: '/reader/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderHistoryRoute = ReaderHistoryRouteImport.update({
  id: '/reader/history',
  path: '/reader/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideosRoute,
} as any)
const WriterIndexRoute = WriterIndexRouteImport.update({
  id: '/writer/',
  path: '/writer/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterAnalyticsRoute = WriterAnalyticsRouteImport.update({
  id: '/writer/analytics',
  path: '/writer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterProfileRoute = WriterProfileRouteImport.update({
  id: '/writer/profile',
  path: '/writer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterSeriesRoute = WriterSeriesRouteImport.update({
  id: '/writer/series',
  path: '/writer/series',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterStoriesRoute = WriterStoriesRouteImport.update({
  id: '/writer/stories',
  path: '/writer/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const WritersIndexRoute = WritersIndexRouteImport.update({
  id: '/writers/',
  path: '/writers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritersSlugRoute = WritersSlugRouteImport.update({
  id: '/writers/$slug',
  path: '/writers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorIndexRoute = AdminEditorIndexRouteImport.update({
  id: '/admin/editor/',
  path: '/admin/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWritersIndexRoute = AdminWritersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWritersRoute,
} as any)
const AdminWritersSlugRoute = AdminWritersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminWritersRoute,
} as any)
const WriterEditorIndexRoute = WriterEditorIndexRouteImport.update({
  id: '/writer/editor/',
  path: '/writer/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterEditorStoryIdRoute = WriterEditorStoryIdRouteImport.update({
  id: '/writer/editor/$storyId',
  path: '/writer/editor/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/terms': typeof TermsRoute
  '/upcoming-projects': typeof UpcomingProjectsRoute
  '/videos': typeof VideosRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/homepage-builder': typeof AdminHomepageBuilderRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/review-queue': typeof AdminReviewQueueRoute
  '/admin/upcoming-projects': typeof AdminUpcomingProjectsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/writers': typeof AdminWritersRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/reader/bookmarks': typeof ReaderBookmarksRoute
  '/reader/following': typeof ReaderFollowingRoute
  '/reader/history': typeof ReaderHistoryRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/writer/analytics': typeof WriterAnalyticsRoute
  '/writer/profile': typeof WriterProfileRoute
  '/writer/series': typeof WriterSeriesRoute
  '/writer/stories': typeof WriterStoriesRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/reader/': typeof ReaderIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/writer/': typeof WriterIndexRoute
  '/writers/': typeof WritersIndexRoute
  '/admin/writers/$slug': typeof AdminWritersSlugRoute
  '/writer/editor/$storyId': typeof WriterEditorStoryIdRoute
  '/admin/editor/': typeof AdminEditorIndexRoute
  '/admin/writers/': typeof AdminWritersIndexRoute
  '/writer/editor/': typeof WriterEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/terms': typeof TermsRoute
  '/upcoming-projects': typeof UpcomingProjectsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/homepage-builder': typeof AdminHomepageBuilderRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/review-queue': typeof AdminReviewQueueRoute
  '/admin/upcoming-projects': typeof AdminUpcomingProjectsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/reader/bookmarks': typeof ReaderBookmarksRoute
  '/reader/following': typeof ReaderFollowingRoute
  '/reader/history': typeof ReaderHistoryRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/writer/analytics': typeof WriterAnalyticsRoute
  '/writer/profile': typeof WriterProfileRoute
  '/writer/series': typeof WriterSeriesRoute
  '/writer/stories': typeof WriterStoriesRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/reader': typeof ReaderIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/videos': typeof VideosIndexRoute
  '/writer': typeof WriterIndexRoute
  '/writers': typeof WritersIndexRoute
  '/admin/writers/$slug': typeof AdminWritersSlugRoute
  '/writer/editor/$storyId': typeof WriterEditorStoryIdRoute
  '/admin/editor': typeof AdminEditorIndexRoute
  '/admin/writers': typeof AdminWritersIndexRoute
  '/writer/editor': typeof WriterEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/terms': typeof TermsRoute
  '/upcoming-projects': typeof UpcomingProjectsRoute
  '/videos': typeof VideosRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/homepage-builder': typeof AdminHomepageBuilderRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/review-queue': typeof AdminReviewQueueRoute
  '/admin/upcoming-projects': typeof AdminUpcomingProjectsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/writers': typeof AdminWritersRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/reader/bookmarks': typeof ReaderBookmarksRoute
  '/reader/following': typeof ReaderFollowingRoute
  '/reader/history': typeof ReaderHistoryRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/writer/analytics': typeof WriterAnalyticsRoute
  '/writer/profile': typeof WriterProfileRoute
  '/writer/series': typeof WriterSeriesRoute
  '/writer/stories': typeof WriterStoriesRoute
  '/writers/$slug': typeof WritersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/reader/': typeof ReaderIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/writer/': typeof WriterIndexRoute
  '/writers/': typeof WritersIndexRoute
  '/admin/writers/$slug': typeof AdminWritersSlugRoute
  '/writer/editor/$storyId': typeof WriterEditorStoryIdRoute
  '/admin/editor/': typeof AdminEditorIndexRoute
  '/admin/writers/': typeof AdminWritersIndexRoute
  '/writer/editor/': typeof WriterEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/categories'
    | '/coming-soon'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/series'
    | '/terms'
    | '/upcoming-projects'
    | '/videos'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/faq'
    | '/admin/homepage-builder'
    | '/admin/profile'
    | '/admin/review-queue'
    | '/admin/upcoming-projects'
    | '/admin/videos'
    | '/admin/writers'
    | '/blogs/$slug'
    | '/reader/bookmarks'
    | '/reader/following'
    | '/reader/history'
    | '/stories/$slug'
    | '/videos/$slug'
    | '/writer/analytics'
    | '/writer/profile'
    | '/writer/series'
    | '/writer/stories'
    | '/writers/$slug'
    | '/admin/'
    | '/blogs/'
    | '/reader/'
    | '/stories/'
    | '/videos/'
    | '/writer/'
    | '/writers/'
    | '/admin/writers/$slug'
    | '/writer/editor/$storyId'
    | '/admin/editor/'
    | '/admin/writers/'
    | '/writer/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/categories'
    | '/coming-soon'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/series'
    | '/terms'
    | '/upcoming-projects'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/faq'
    | '/admin/homepage-builder'
    | '/admin/profile'
    | '/admin/review-queue'
    | '/admin/upcoming-projects'
    | '/admin/videos'
    | '/blogs/$slug'
    | '/reader/bookmarks'
    | '/reader/following'
    | '/reader/history'
    | '/stories/$slug'
    | '/videos/$slug'
    | '/writer/analytics'
    | '/writer/profile'
    | '/writer/series'
    | '/writer/stories'
    | '/writers/$slug'
    | '/admin'
    | '/blogs'
    | '/reader'
    | '/stories'
    | '/videos'
    | '/writer'
    | '/writers'
    | '/admin/writers/$slug'
    | '/writer/editor/$storyId'
    | '/admin/editor'
    | '/admin/writers'
    | '/writer/editor'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blogs'
    | '/categories'
    | '/coming-soon'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/search'
    | '/series'
    | '/terms'
    | '/upcoming-projects'
    | '/videos'
    | '/admin/analytics'
    | '/admin/blogs'
    | '/admin/faq'
    | '/admin/homepage-builder'
    | '/admin/profile'
    | '/admin/review-queue'
    | '/admin/upcoming-projects'
    | '/admin/videos'
    | '/admin/writers'
    | '/blogs/$slug'
    | '/reader/bookmarks'
    | '/reader/following'
    | '/reader/history'
    | '/stories/$slug'
    | '/videos/$slug'
    | '/writer/analytics'
    | '/writer/profile'
    | '/writer/series'
    | '/writer/stories'
    | '/writers/$slug'
    | '/admin/'
    | '/blogs/'
    | '/reader/'
    | '/stories/'
    | '/videos/'
    | '/writer/'
    | '/writers/'
    | '/admin/writers/$slug'
    | '/writer/editor/$storyId'
    | '/admin/editor/'
    | '/admin/writers/'
    | '/writer/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  TermsRoute: typeof TermsRoute
  UpcomingProjectsRoute: typeof UpcomingProjectsRoute
  VideosRoute: typeof VideosRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminHomepageBuilderRoute: typeof AdminHomepageBuilderRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReviewQueueRoute: typeof AdminReviewQueueRoute
  AdminUpcomingProjectsRoute: typeof AdminUpcomingProjectsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminWritersRoute: typeof AdminWritersRouteWithChildren
  ReaderBookmarksRoute: typeof ReaderBookmarksRoute
  ReaderFollowingRoute: typeof ReaderFollowingRoute
  ReaderHistoryRoute: typeof ReaderHistoryRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  WriterAnalyticsRoute: typeof WriterAnalyticsRoute
  WriterProfileRoute: typeof WriterProfileRoute
  WriterSeriesRoute: typeof WriterSeriesRoute
  WriterStoriesRoute: typeof WriterStoriesRoute
  WritersSlugRoute: typeof WritersSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ReaderIndexRoute: typeof ReaderIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  WriterIndexRoute: typeof WriterIndexRoute
  WritersIndexRoute: typeof WritersIndexRoute
  WriterEditorStoryIdRoute: typeof WriterEditorStoryIdRoute
  AdminEditorIndexRoute: typeof AdminEditorIndexRoute
  WriterEditorIndexRoute: typeof WriterEditorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-projects': {
      id: '/upcoming-projects'
      path: '/upcoming-projects'
      fullPath: '/upcoming-projects'
      preLoaderRoute: typeof UpcomingProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/homepage-builder': {
      id: '/admin/homepage-builder'
      path: '/admin/homepage-builder'
      fullPath: '/admin/homepage-builder'
      preLoaderRoute: typeof AdminHomepageBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review-queue': {
      id: '/admin/review-queue'
      path: '/admin/review-queue'
      fullPath: '/admin/review-queue'
      preLoaderRoute: typeof AdminReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upcoming-projects': {
      id: '/admin/upcoming-projects'
      path: '/admin/upcoming-projects'
      fullPath: '/admin/upcoming-projects'
      preLoaderRoute: typeof AdminUpcomingProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/writers': {
      id: '/admin/writers'
      path: '/admin/writers'
      fullPath: '/admin/writers'
      preLoaderRoute: typeof AdminWritersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/reader/': {
      id: '/reader/'
      path: '/reader'
      fullPath: '/reader/'
      preLoaderRoute: typeof ReaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/bookmarks': {
      id: '/reader/bookmarks'
      path: '/reader/bookmarks'
      fullPath: '/reader/bookmarks'
      preLoaderRoute: typeof ReaderBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/following': {
      id: '/reader/following'
      path: '/reader/following'
      fullPath: '/reader/following'
      preLoaderRoute: typeof ReaderFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/history': {
      id: '/reader/history'
      path: '/reader/history'
      fullPath: '/reader/history'
      preLoaderRoute: typeof ReaderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof VideosRoute
    }
    '/writer/': {
      id: '/writer/'
      path: '/writer'
      fullPath: '/writer/'
      preLoaderRoute: typeof WriterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/analytics': {
      id: '/writer/analytics'
      path: '/writer/analytics'
      fullPath: '/writer/analytics'
      preLoaderRoute: typeof WriterAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/profile': {
      id: '/writer/profile'
      path: '/writer/profile'
      fullPath: '/writer/profile'
      preLoaderRoute: typeof WriterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/series': {
      id: '/writer/series'
      path: '/writer/series'
      fullPath: '/writer/series'
      preLoaderRoute: typeof WriterSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/stories': {
      id: '/writer/stories'
      path: '/writer/stories'
      fullPath: '/writer/stories'
      preLoaderRoute: typeof WriterStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writers/': {
      id: '/writers/'
      path: '/writers'
      fullPath: '/writers/'
      preLoaderRoute: typeof WritersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writers/$slug': {
      id: '/writers/$slug'
      path: '/writers/$slug'
      fullPath: '/writers/$slug'
      preLoaderRoute: typeof WritersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/': {
      id: '/admin/editor/'
      path: '/admin/editor'
      fullPath: '/admin/editor/'
      preLoaderRoute: typeof AdminEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/writers/': {
      id: '/admin/writers/'
      path: '/'
      fullPath: '/admin/writers/'
      preLoaderRoute: typeof AdminWritersIndexRouteImport
      parentRoute: typeof AdminWritersRoute
    }
    '/admin/writers/$slug': {
      id: '/admin/writers/$slug'
      path: '/$slug'
      fullPath: '/admin/writers/$slug'
      preLoaderRoute: typeof AdminWritersSlugRouteImport
      parentRoute: typeof AdminWritersRoute
    }
    '/writer/editor/': {
      id: '/writer/editor/'
      path: '/writer/editor'
      fullPath: '/writer/editor/'
      preLoaderRoute: typeof WriterEditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/editor/$storyId': {
      id: '/writer/editor/$storyId'
      path: '/writer/editor/$storyId'
      fullPath: '/writer/editor/$storyId'
      preLoaderRoute: typeof WriterEditorStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface VideosRouteChildren {
  VideosSlugRoute: typeof VideosSlugRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosSlugRoute: VideosSlugRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

interface AdminWritersRouteChildren {
  AdminWritersSlugRoute: typeof AdminWritersSlugRoute
  AdminWritersIndexRoute: typeof AdminWritersIndexRoute
}

const AdminWritersRouteChildren: AdminWritersRouteChildren = {
  AdminWritersSlugRoute: AdminWritersSlugRoute,
  AdminWritersIndexRoute: AdminWritersIndexRoute,
}

const AdminWritersRouteWithChildren = AdminWritersRoute._addFileChildren(
  AdminWritersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  TermsRoute: TermsRoute,
  UpcomingProjectsRoute: UpcomingProjectsRoute,
  VideosRoute: VideosRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminHomepageBuilderRoute: AdminHomepageBuilderRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReviewQueueRoute: AdminReviewQueueRoute,
  AdminUpcomingProjectsRoute: AdminUpcomingProjectsRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminWritersRoute: AdminWritersRouteWithChildren,
  ReaderBookmarksRoute: ReaderBookmarksRoute,
  ReaderFollowingRoute: ReaderFollowingRoute,
  ReaderHistoryRoute: ReaderHistoryRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  WriterAnalyticsRoute: WriterAnalyticsRoute,
  WriterProfileRoute: WriterProfileRoute,
  WriterSeriesRoute: WriterSeriesRoute,
  WriterStoriesRoute: WriterStoriesRoute,
  WritersSlugRoute: WritersSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ReaderIndexRoute: ReaderIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  WriterIndexRoute: WriterIndexRoute,
  WritersIndexRoute: WritersIndexRoute,
  WriterEditorStoryIdRoute: WriterEditorStoryIdRoute,
  AdminEditorIndexRoute: AdminEditorIndexRoute,
  WriterEditorIndexRoute: WriterEditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
